name: Deploy
description: Deploy to GCP
inputs:
  project_id:
    description: "The GCP project ID"
    required: true
  identity_provider:
    description: "The identity provider for the workload identity"
    required: true
  service_account_email:
    description: "The service account email"
    required: true

runs:
  using: composite
  steps:
    - name: 🗝️ Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.identity_provider }}
        service_account: ${{ inputs.service_account_email }}
        token_format: "access_token"

    - name: 🚀 Deploy Main Skid Cloud Function
      id: deploy-skid
      uses: google-github-actions/deploy-cloud-functions@v4
      with:
        name: state-parks-skid
        runtime: python313
        entry_point: process
        source_dir: src/state_parks
        service_account: cloud-function-sa@${{ inputs.project_id }}.iam.gserviceaccount.com
        memory: 1024M
        service_timeout: 9m
        secrets: |
          /secrets/app/secrets.json=${{ inputs.project_id }}/skid-secrets
        max_instance_count: 1
        event_trigger_retry: false

    - name: 🚀 Deploy Webhook Trigger Cloud Function
      id: deploy-webhook
      uses: google-github-actions/deploy-cloud-functions@v4
      with:
        name: webhook-trigger
        runtime: python313
        entry_point: trigger
        source_dir: src/webhook_trigger
        service_account: cloud-function-sa@${{ inputs.project_id }}.iam.gserviceaccount.com
        memory: 1024M
        service_timeout: 9m
        secrets: |
          /secrets/app/secrets.json=${{ inputs.project_id }}/skid-secrets
        max_instance_count: 1
        event_trigger_retry: false
